### ISSUE TITLE
checksum error processing cloud-config: copy cloud config task

### ISSUE THREAD

**Issue by upolymorph** [cornelius-keller/ansible-coreos-kubernetes#6]
Running the bootstrap_coreos playbook I get this error

TASK [cloud-config : copy cloud config] ****************************************
Wednesday 04 January 2017  08:49:53 +0100 (0:00:00.015)       0:03:39.825 ***** 
fatal: [xx.xx.xx.xx]: FAILED! => {"changed": false, "failed": true, "msg": "failed to checksum remote file. Checksum error code: 4"}

Despite several search I am not able to figure out what is the route cause of this error nor how to debug it.

**Comment by cornelius-keller** [comment]
Hi @upolymorph,

I need a bit more context. Can you attach the full log?

Am 04.01.2017 9:15 vorm. schrieb "upolymorph" <notifications@github.com>:

Running the bootstrap_coreos playbook I get this error

TASK [cloud-config : copy cloud config] ******************************
**********
Wednesday 04 January 2017 08:49:53 +0100 (0:00:00.015) 0:03:39.825 *****
fatal: [88.99.56.238]: FAILED! => {"changed": false, "failed": true, "msg":
"failed to checksum remote file. Checksum error code: 4"}

Despite several search I am not able to figure out what is the route cause
of this error nor how to debug it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cornelius-keller/ansible-coreos-kubernetes/issues/6>,
or mute the thread

**Comment by cornelius-keller** [comment]
Which ansible version are you using?

I tested with 2.1 and 2.2 recently. If you are using an older ansible
version you might be running into this one:
https://github.com/ansible/ansible/issues/11968 .

Am 04.01.2017 9:31 vorm. schrieb "Cornelius Keller" <
cornelius.keller@gmail.com>:

**Comment by upolymorph** [comment]
well spotted I am using 2.0.0.2 (default ubuntu package). Will try to upgrade and keep you updated.

**Comment by upolymorph** [comment]
Now I have a new error in a previous task

TASK [ansible-coreos-bootstrap : Load bootstrap facts] *************************
Wednesday 04 January 2017  10:00:43 +0100 (0:00:20.100)       0:03:48.432 ***** 
fatal: [xx.xx.xx.xx]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to xx.xx.xx.xx closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/core/.ansible/tmp/ansible-tmp-1483520443.79-265783318867070/setup.py\", line 130, in <module>\r\n    exitcode = invoke_module(module, zipped_mod, ANSIBALLZ_PARAMS)\r\n  File \"/home/core/.ansible/tmp/ansible-tmp-1483520443.79-265783318867070/setup.py\", line 37, in invoke_module\r\n    p = subprocess.Popen(['PATH=/home/core/bin:$PATH', 'python', module], env=os.environ, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE)\r\n  File \"/home/core/.pypy/lib-python/2.7/subprocess.py\", line 725, in __init__\r\n    errread, errwrite)\r\n  File \"/home/core/.pypy/lib-python/2.7/subprocess.py\", line 1354, in _execute_child\r\n    raise child_exception\r\nOSError: [Errno 2] No such file or directory\r\n", "msg": "MODULE FAILURE"}

**Comment by cornelius-keller** [comment]
Can you somehow send me the full log?

Am 04.01.2017 10:03 schrieb "upolymorph" <notifications@github.com>:

**Comment by upolymorph** [comment]
Was using an incorrect ansible_python_interpreter definition due to old ansible version. I solved the issue by using updated ansible_python_interpreter in inventory ini file.

To avoid this kind of issue can we add a test to check ansible version and ensure version is >= 2.1?

**Comment by upolymorph** [comment]
I have been able to run through the full playbook even though the etcd cluster is not working. But at least this issue can be closed. Thanks for your help !
